# Generated by Django 4.2 on 2025-10-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=100, null=True)),
                ('product_name', models.CharField(blank=True, max_length=255, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('current_stock', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_deal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_free', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purc_deal', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purc_free', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=255, null=True)),
                ('rec_date', models.DateField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=100, null=True)),
                ('exp', models.DateField(blank=True, null=True)),
                ('supplier', models.CharField(blank=True, max_length=255, null=True)),
                ('inv_no', models.CharField(blank=True, max_length=100, null=True)),
                ('inv_date', models.DateField(blank=True, null=True)),
                ('rack_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
