# Generated by Django 4.2.24 on 2025-10-07 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_inventory_customer_address_alter_customer_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
