# Generated by Django 4.2.24 on 2025-10-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_uploadedexcel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, db_index=True, max_length=100)),
                ('product_name', models.CharField(blank=True, max_length=255)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('sales_scheme_deal', models.CharField(blank=True, max_length=100)),
                ('sales_scheme_free', models.CharField(blank=True, max_length=100)),
                ('purc_scheme_deal', models.CharField(blank=True, max_length=100)),
                ('purc_scheme_free', models.CharField(blank=True, max_length=100)),
                ('cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('sales_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('company', models.CharField(blank=True, max_length=200)),
                ('manufacturer', models.CharField(blank=True, max_length=200)),
                ('rec_date', models.DateField(blank=True, null=True)),
                ('batch', models.CharField(blank=True, max_length=100)),
                ('exp', models.DateField(blank=True, null=True, verbose_name='Expiry')),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('inv_no', models.CharField(blank=True, max_length=100)),
                ('inv_date', models.DateField(blank=True, null=True)),
                ('rack_no', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='UploadedExcel',
        ),
    ]
